<?php 


/**
 * Implements hook_menu().
 */
 
function find_congressman_menu() {
	$items = array();
	$items['admin/config/content/find_congressman'] = array(
		'title' => 'Find Your Congressman',
		'description' => 'Configuration for Find Your Congressman module. Includes Sunlight Foundation API Key.',
		'page callback' => 'drupal_get_form',
		'page arguments' => array('find_congressman_form'),
		'access arguments' => array('access administration pages'),
		'type' => MENU_NORMAL_ITEM,
	);
 
	$items['find_congressman'] = array(
		'title' => 'Find Your Congressman',
		'page callback' => '_page_find_congressman',
		'access callback' => TRUE,
		'type' => MENU_SUGGESTED_ITEM,
	);  
  
  return $items;
} 

function _page_find_congressman() {
  return array(
    '#markup' => find_congressman_contents()
  );
}

/**
 * Page callback: Current posts settings
 *
 * @see find_congressman_menu()
 */
function find_congressman_form($form, &$form_state) {
	$form = array();
	$form['find_congressman'] = array(
		'#type' => 'textfield',
		'#title' => t('Sunlight Foundation API Key'),
		'#default_value' => variable_get('find_congressman', 1),
		'#size' => 100,
		'#maxlength' => 100,
		'#description' => t('If you don\'t have an API key, please go to this URL to get one: http://sunlightfoundation.com/api/accounts/register/'),
		'#required' => TRUE,
	);
/*
	$form['find_congressman_checks'] = array(
		'#type' => 'item', 
		'#title' => t('Which features would you like to display?'),
		'#description' => t('Select all of the features that you\'d like to display on the "Find Your Congressman" page.'),
		'#required' => FALSE,
	);
*/
	$form['congressman_features'] = array(
		'#type' => 'checkboxes',
		'#title' => t('Which features would you like to display?'),
		'#description' => t('Select all of the features that you\'d like to display on the "Find Your Congressman" page.'),		
		'#options' => drupal_map_assoc(array(
			t('Affiliated Party'),
			t('Chamber'),
			t('District'),	
			t('Facebook Page Link'),
			t('Fax Number'),												
			t('Image'),
			t('Link to Website Contact Form'),
			t('Name'),			
			t('Open Congress Email'),	
			t('Phone Number'),
			t('State'),
			t('Title'),	
			t('Top State Name'),			
			t('Twitter Page Link'),
			t('Youtube Page Link'),																	
		)),
		'#default_value' => variable_get('congressman_features', 1),
	);
  return system_settings_form($form);
}	

/**
 * custom html block
 * @return string
 */
function find_congressman_contents() {

$apikey = variable_get('find_congressman',1);

$zipcode = $_GET["zip"];

// construct the query with our apikey and the query we want to make
$endpoint = 'https://congress.api.sunlightfoundation.com/legislators/locate?zip='. $zipcode .'&apikey=' . $apikey;

// setup curl to make a call to the endpoint
$session = curl_init($endpoint);

// indicates that we want the response back
curl_setopt($session, CURLOPT_RETURNTRANSFER, true);

// exec curl and get the data back
$data = curl_exec($session);

// remember to close the curl session once we are finished retrieveing the data
curl_close($session);

// decode the json data to make it easier to parse the php
$search_results = json_decode($data);
if ($search_results === NULL) die('Error parsing json');

/* print_r($search_results); */

	if (empty($search_results->results)) {
	
		$content = '<div class="large-12 columns alert-box alert">Please Check your zip code and make sure it is a 5 digit US Postal Zip.</div>';
		$content .= '<br><br><br><br>';
		return $content;	
		
	} else {
	// play with the data!
		$congressmen = $search_results->results;
	
		$content = "<div class=\"congress-wrap row\">";
		$congress_checks = variable_get('congressman_features');	
		$content .= '<ul class="large-12 columns">';
			if ($congress_checks['Top State Name']){
				$content .=  '<h4>' . $congressmen[0]->state_name . '</h4>';
			}			
			foreach ($congressmen as $congress) {
				if ($congress_checks['Name']){
					$content .=  '<li class="congressman"><div><a href="' . $congress->website . '" target="_blank">' . $congress->first_name .' '. $congress->last_name . "</a></div>";
				}					
				if ($congress_checks['Image']){
					$content .= '<img src="http://theunitedstates.io/images/congress/225x275/' . $congress->bioguide_id . '.jpg">';				
				}	
				if ($congress_checks['Affiliated Party']){
					$content .= '<div>Party: ' . $congress->party . '</div>';				
				}				
				if ($congress_checks['District']){
					$content .= '<div>District: ' . $congress->district . '</div>';					
				}							
				if ($congress_checks['Chamber']){
					$content .= '<div>Chamber: ' . $congress->chamber . '</div>';					
				}
				if ($congress_checks['Open Congress Email']){
					$content .= '<div>Open Congress Email: ' . $congress->oc_email . '</div>';					
				}									
				if ($congress_checks['Facebook Page Link']){
					$content .= '<div>Facebook: <a href="https://www.facebook.com/' . $congress->facebook_id . '" target="_blank">Facebook Page</a></div>';					
				}					
				if ($congress_checks['Phone Number']){
					$content .= '<div>Phone: ' . $congress->phone . '</div>';					
				}
				if ($congress_checks['Fax Number']){
					$content .= '<div>Fax: ' . $congress->fax . '</div>';					
				}					
				if ($congress_checks['Link to Website Contact Form']){
					$content .= '<div><a href="' . $congress->contact_form . '" target="_blank">Contact Form</a></div>';					
				}								
				$content .= '</li>';
			}
		$content .= '</ul>';
		
		return $content;
	}
	
}

function find_congressman_zip() {

	drupal_add_js(drupal_get_path('module', 'find_congressman') .'/js/find-congressman.js');
	
	$content = "<div class=\"find-zip row\">";
	
		$content .= '<div class="columns">';
			$content .=  '<div class="subheader">Please enter a 5 digit zipcode</div>';  		
			$content .=  '<input id="zipcode-value" class="zipcode-field" type="text" name="zip" maxlength="5">'; 
			$content .=  '<input type="submit" value="Search" class="zip-button">'; 						
		$content .= '</div>';
		
		return $content;

}

/**
 * Implements hook_block_info().
 */
function find_congressman_block_info() {
  $blocks['find_congressman_block_1'] = array(
    'info' => t('Find Your Congressman 2'),
    'cache' => DRUPAL_NO_CACHE,
  );
  $blocks['find_congressman_block_2'] = array(
    'info' => t('Find Your Congressman Zip'),
    'cache' => DRUPAL_NO_CACHE,
  );  
  return $blocks;
}
 
/**
 * Implements hook_block_view().
 */
function find_congressman_block_view($delta = '') {
  $block = array();
  switch ($delta) {
    case 'find_congressman_block_1':
      $block['subject'] = t('Find Your Congressman');
      $block['content'] = find_congressman_contents();
      break;
    case 'find_congressman_block_2': 
      $block['subject'] = t('Find Your Congressman');
      $block['content'] = find_congressman_zip();      
  }
  return $block;
}

?>