<?php 


/**
 * Implements hook_menu().
 */
 
function find_congressperson_menu() {
	$items = array();
	$items['admin/config/content/find_congressperson'] = array(
		'title' => 'Find Your Congressperson',
		'description' => 'Configuration for Find Your Congressperson module. Includes Sunlight Foundation API Key and Google Geocode API Key fields.',
		'page callback' => 'drupal_get_form',
		'page arguments' => array('find_congressperson_form'),
		'access arguments' => array('access administration pages'),
		'type' => MENU_NORMAL_ITEM,
	);
 
	$items['find_congressperson_zip'] = array(
		'title' => 'Find Your Congressperson',
		'page callback' => '_page_find_congressperson',
		'access callback' => TRUE,
		'type' => MENU_SUGGESTED_ITEM,
	);  
 
	$items['find_congressperson_address'] = array(
		'title' => 'Find Your Congressperson',
		'page callback' => '_page_find_congressperson_address',
		'access callback' => TRUE,
		'type' => MENU_SUGGESTED_ITEM,
	); 

	$items['find_congressperson_name'] = array(
		'title' => 'Find Your Congressperson',
		'page callback' => '_page_find_congressperson_name',
		'access callback' => TRUE,
		'type' => MENU_SUGGESTED_ITEM,
	); 
  
	$items['congressperson'] = array(
		'title' => 'Congressperson',
		'page callback' => '_page_congressperson',
		'access callback' => TRUE,
		'type' => MENU_SUGGESTED_ITEM,
	);   
  
  return $items;
} 

function _page_find_congressperson() {
  return array(
    '#markup' => find_congressperson_contents()
  );
}

function _page_find_congressperson_address() {
  return array(
    '#markup' => find_congressperson_address_contents()
  );
}

function _page_find_congressperson_name() {
  return array(
    '#markup' => find_congressperson_name_contents()
  );
}

function _page_congressperson() {
  return array(
    '#markup' => congressperson()
  );
}

/**
 * Page callback: Current posts settings
 *
 * @see find_congressperson_menu()
 */
function find_congressperson_form($form, &$form_state) {
	$form = array();
	$form['find_congressperson'] = array(
		'#type' => 'textfield',
		'#title' => t('Sunlight Foundation API Key'),
		'#default_value' => variable_get('find_congressperson'),
		'#size' => 100,
		'#maxlength' => 100,
		'#description' => t('If you don\'t have an API key, please go to this URL to get one: <a href="http://sunlightfoundation.com/api/accounts/register/" target="blank">http://sunlightfoundation.com/api/accounts/register/</a>'),
		'#required' => TRUE,
	);

	$form['find_by_address'] = array(
		'#type' => 'textfield',
		'#title' => t('Google Geocoding API Key'),
		'#default_value' => variable_get('find_by_address'),
		'#size' => 100,
		'#maxlength' => 100,
		'#description' => t('This is for looking up the Congressperson by Address. If you don\'t have a Google Geocoding API key, please follow these directions:<br><ol><li>Visit the APIs console at <a href="https://code.google.com/apis/console" target="blank">https://code.google.com/apis/console</a> and log in with your Google Account.</li><li>Click the Services link from the left-hand menu in the APIs Console, then activate the Geocoding API service.</li><li>Once the service has been activated, your API key is available from the API Access page, in the Simple API Access section. Geocoding API applications use the Key for server apps.</li></ol>'),
		'#required' => TRUE,
	);

	$form['congressperson_features'] = array(
		'#type' => 'checkboxes',
		'#title' => t('Which features would you like to display?'),
		'#description' => t('Select all of the features that you\'d like to display on the "Find Your Congressperson" page.'),		
		'#options' => drupal_map_assoc(array(
			t('Affiliated Party'),
			t('Chamber'),
			t('District'),	
			t('Facebook Page Link'),
			t('Fax Number'),												
			t('Image'),
			t('Link to Website Contact Form'),
			t('Name'),			
			t('Open Congress Email'),	
			t('Phone Number'),
			t('State'),
			t('Title'),				
			t('Twitter Page Link'),
			t('Youtube Page Link'),																	
		)),
		'#default_value' => variable_get('congressperson_features'),
	);
	$form['congressperson_tweets'] = array(
		'#type' => 'fieldset',
		'#title' => t('Twitter API'),
		'#description' => t('This is for showing recent Tweets by a Congressperson. <br>If you don\'t have an API key, please go to this URL to get one: <a href="https://apps.twitter.com/" target="_blank">https://apps.twitter.com/</a>'),	
		'#default_value' => $congressperson_tweets, 				
		'#collapsible' => TRUE,
		'#collapsed' => FALSE, 		
		'#tree' => TRUE,
	);
	$form['congressperson_tweets']['oauth'] = array(
	    '#type' => 'textfield',
	    '#title' => t('OAuth Access Token'),
		'#default_value' => variable_get('oauth'),	    	    	    
		'#required' => FALSE,
	);
	$form['congressperson_tweets']['secret'] = array(
	    '#type' => 'textfield',
	    '#title' => t('OAuth Access Token Secret'),
		'#default_value' => variable_get('secret'),
		'#required' => FALSE,	
	);
	$form['congressperson_tweets']['key'] = array(
	    '#type' => 'textfield',
	    '#title' => t('Consumer Key'), 
		'#default_value' => $node->key,
		'#required' => FALSE,	
	);	
	$form['congressperson_tweets']['consumer'] = array(
	    '#type' => 'textfield',
	    '#title' => t('Consumer Secret'),
		'#required' => FALSE,		
	);		

  return system_settings_form($form);
}	

/**
 * custom html block
 * @return string
 */
 
// Search results content page for zipcode search
function find_congressperson_contents() {

	$apikey = variable_get('find_congressperson');
	
	$zipcode = isset($_GET["zip"]) ? $_GET["zip"] : 0;
	
	// construct the query with our apikey and the query we want to make
	$endpoint = 'https://congress.api.sunlightfoundation.com/legislators/locate?zip='. $zipcode .'&apikey=' . $apikey;
	
	// setup curl to make a call to the endpoint
	$session = curl_init($endpoint);
	
	// indicates that we want the response back
	curl_setopt($session, CURLOPT_RETURNTRANSFER, true);
	
	// exec curl and get the data back
	$data = curl_exec($session);
	
	// remember to close the curl session once we are finished retrieveing the data
	curl_close($session);
	
	// decode the json data to make it easier to parse the php
	$search_results = json_decode($data);
	if ($search_results === NULL) die('Error parsing json = Endpoint Error');
	
	if (empty($search_results->results)) {
	
		$content = '<div class="large-12 columns alert-box alert">Please check your zip code and make sure it is a 5 digit US Postal Zip Code.</div>';
		$content .= '<br><br><br><br>';
		return $content;	
				
	} else {
	// play with the data!
		$congressperson = $search_results->results;

		drupal_set_title(t($congressperson[0]->state_name));
	
		$content = "<div class=\"congress-wrap row\">";
		$congress_checks = variable_get('congressperson_features');	
		$content .= '<ul class="large-12 columns">';		
			foreach ($congressperson as $congress) {
				if ($congress_checks['Name']){
					$content .=  '<li class="congressperson"><div><a href="/congressperson?first_name=' . $congress->first_name . '&last_name='. $congress->last_name .'&bioguide_id=' . $congress->bioguide_id .'">' . $congress->first_name .' '. $congress->last_name . "</a></div>";
				}					
				if ($congress_checks['Image']){
					$content .= '<img src="http://theunitedstates.io/images/congress/225x275/' . $congress->bioguide_id . '.jpg">';				
				}	
				if ($congress_checks['Affiliated Party']){
					$content .= '<div>Party: ' . $congress->party . '</div>';				
				}				
				if ($congress_checks['District']){
					if (isset($address->district)) {
						$content .= '<div>District: ' . $address->district . '</div>';
					}
				}								
				if ($congress_checks['Chamber']){
					$content .= '<div>Chamber: ' . $congress->chamber . '</div>';					
				}
				if ($congress_checks['Open Congress Email']){
					$content .= '<div>Open Congress Email: ' . $congress->oc_email . '</div>';					
				}									
				if ($congress_checks['Facebook Page Link']){
					$content .= '<div>Facebook: <a href="https://www.facebook.com/' . $congress->facebook_id . '" target="_blank">Facebook Page</a></div>';					
				}					
				if ($congress_checks['Phone Number']){
					$content .= '<div>Phone: ' . $congress->phone . '</div>';					
				}
				if ($congress_checks['Fax Number']){
					$content .= '<div>Fax: ' . $congress->fax . '</div>';					
				}					
				if ($congress_checks['Link to Website Contact Form']){
					$content .= '<div><a href="' . $congress->contact_form . '" target="_blank">Contact Form</a></div>';					
				}
				if ($congress_checks['Youtube Page Link']){
					$content .= '<div><a href="https://www.youtube.com/' . $congress->youtube_id . '" target="_blank">YouTube</a></div>';					
				}
				if ($congress_checks['Twitter Page Link']){
					$content .= '<div><a href="https://twitter.com/' . $congress->twitter_id . '" target="_blank">Twitter</a></div>';					
				}												
				$content .= '</li>';
			}
		$content .= '</ul>';
		
		return $content;
	}	
}

// Search results content page for address search
function find_congressperson_address_contents() {

	$geoapikey = variable_get('find_by_address');
	$apikey = variable_get('find_congressperson');

	$address = urlencode(isset($_GET["address"]) ? $_GET["address"] : 0);
	
	// construct the query with our apikey and the query we want to make
	$geoendpoint = 'https://maps.googleapis.com/maps/api/geocode/json?address='. $address .'&key=' .$geoapikey;
	
	// setup curl to make a call to the endpoint
	$session2 = curl_init($geoendpoint);
	
	// indicates that we want the response back
	curl_setopt($session2, CURLOPT_RETURNTRANSFER, true);
	
	// exec curl and get the data back
	$data2 = curl_exec($session2);
	
	// remember to close the curl session once we are finished retrieveing the data
	curl_close($session2);
	
	// decode the json data to make it easier to parse the php
	$geo_results = json_decode($data2);
/* 	if ($geo_results === NULL) die('Error parsing json = Geo Endpoint Error'); */
	
	if ($geo_results->status === 'ZERO_RESULTS') {
	
		$content = '<div class="large-12 columns alert-box alert">Please check your address and make sure it is correctly formatted. All fields must be completed.</div>';
		$content .= '<br><br><br><br>';
		return $content;
						
	}
	
	$lat = $geo_results->results[0]->geometry->location->lat;
	$lng = $geo_results->results[0]->geometry->location->lng;
	
	// Lat/Long API Endpoint
	$latendpoint = 'https://congress.api.sunlightfoundation.com/legislators/locate?latitude='. $lat .'&longitude='. $lng .'&apikey=' . $apikey;
	$session3 = curl_init($latendpoint);
	curl_setopt($session3, CURLOPT_RETURNTRANSFER, true);
	$data3 = curl_exec($session3);
	curl_close($session3);
	
	$lat_results = json_decode($data3);
	if ($lat_results === NULL) die('Error parsing json = Lat/Long Endpoint Error');

	if (empty($lat_results->results)) {
	
		$content = '<div class="large-12 columns alert-box alert">Please check your address and make sure it is correctly formatted.</div>';
		$content .= '<br><br><br><br>';
		return $content;
						
	} else {
		$addressresults = $lat_results->results;
		
		$content = '<span class="congress-state stateface stateface-'. strtolower($addressresults[0]->state) .'" style="font-family: StateFaceRegular;"></span>'; 
		
		$content .= '<div class=\"congress-wrap row\">';
 
		$addy_checks = variable_get('congressperson_features');	
			$content .= '<ul class="large-12 columns">';
			
				if (isset($addressresults->district)) {
					$district = $addressresults->district;
					drupal_set_title(t($addressresults->state_name . ' ( ' . $district . ' )'));					
				}			
			
			foreach ($addressresults as $address) {	     
		       	       
				if ($addy_checks['Name']){
					$content .=  '<li class="congressperson"><div><a href="/congressperson?first_name=' . $address->first_name . '&last_name='. $address->last_name .'&bioguide_id=' . $address->bioguide_id .'">' . $address->first_name .' '. $address->last_name . "</a></div>";
				}								
				if ($addy_checks['Image']){
					$content .= '<img src="http://theunitedstates.io/images/congress/225x275/' . $address->bioguide_id . '.jpg">';
				}	
				if ($addy_checks['Affiliated Party']){
					$content .= '<div>Party: ' . $address->party . '</div>';				
				}				
				if ($addy_checks['District']){
					if (isset($address->district)) {
						$content .= '<div>District: ' . $address->district . '</div>';
					}
				}											
				if ($addy_checks['Chamber']){
					$content .= '<div>Chamber: ' . $address->chamber . '</div>';					
				}
				if ($addy_checks['Open Congress Email']){
					$content .= '<div>Open Congress Email: ' . $address->oc_email . '</div>';					
				}									
				if ($addy_checks['Facebook Page Link']){
				
					if (!array_key_exists($address->facebook_id)) {
						$content .= '<div>Facebook: <a href="https://www.facebook.com/' . $address->facebook_id . '" target="_blank">Facebook Page</a></div>';	
					} else {
					
					}				
				}					
				if ($addy_checks['Phone Number']){
					$content .= '<div>Phone: ' . $address->phone . '</div>';					
				}
				if ($addy_checks['Fax Number']){
					$content .= '<div>Fax: ' . $address->fax . '</div>';					
				}					
				if ($addy_checks['Link to Website Contact Form']){
					$content .= '<div><a href="' . $address->contact_form . '" target="_blank">Contact Form</a></div>';					
				}
				if ($addy_checks['Youtube Page Link']){
					$content .= '<div><a href="https://www.youtube.com/' . $address->youtube_id . '" target="_blank">Youtube</a></div>';					
				}
				if ($addy_checks['Twitter Page Link']){
					$content .= '<div><a href="https://twitter.com/' . $address->twitter_id . '" target="_blank">Twitter</a></div>';					
				}																
				$content .= '</li>';
			}
			
		$content .= '</ul>';
		$content .= '</div>';
		return $content;			
	}
	
}

// Search results content page for address search
function find_congressperson_name_contents() {
	
	$firstname = isset($_GET["firstname"]) ? $_GET["firstname"] : 0;
	$lastname = isset($_GET["lastname"]) ? $_GET["lastname"] : 0;

	drupal_set_title(t($firstname . ' ' . $lastname));

	$apikey = variable_get('find_congressperson');
	
	// construct the query with our apikey and the query we want to make
	$endpoint = 'https://congress.api.sunlightfoundation.com/legislators?first_name=' . $firstname . '&last_name='. $lastname .'&apikey=' . $apikey;
	
	// setup curl to make a call to the endpoint
	$session = curl_init($endpoint);
	
	// indicates that we want the response back
	curl_setopt($session, CURLOPT_RETURNTRANSFER, true);
	
	// exec curl and get the data back
	$data = curl_exec($session);
	
	// remember to close the curl session once we are finished retrieveing the data
	curl_close($session);
	
	// decode the json data to make it easier to parse the php
	$search_results = json_decode($data);
	if ($search_results === NULL) die('Error parsing json = Endpoint Error');
	
	if (empty($search_results->results)) {
	
		$content = '<div class="large-12 columns alert-box alert">Please check the name of the congressperson you are looking for. They may go by a different name or their full name instead of a nickname.</div>';
		$content .= '<br><br><br><br>';
		return $content;	
				
	} else {
	// play with the data!
		$congressperson = $search_results->results;
	
		$content = "<div class=\"congress-wrap row\">";
		$congress_checks = variable_get('congressperson_features');	
		$content .= '<ul class="large-12 columns">';			
			foreach ($congressperson as $congress) {				
				$content .= '<img src="http://theunitedstates.io/images/congress/225x275/' . $congress->bioguide_id . '.jpg">';				
				$content .=  '<div>' . $congress->state_name . '</div>';			
				$content .= '<div>Party: ' . $congress->party . '</div>';						
				if (isset($congress->district)) {
					$content .= '<div>District: ' . $congress->district . '</div>';
				}						
				$content .= '<div>Chamber: ' . $congress->chamber . '</div>';					
				$content .= '<div>Open Congress Email: ' . $congress->oc_email . '</div>';													
				$content .= '<div>Facebook: <a href="https://www.facebook.com/' . $congress->facebook_id . '" target="_blank">Facebook Page</a></div>';
				$content .= '<div>Phone: ' . $congress->phone . '</div>';					
				$content .= '<div>Fax: ' . $congress->fax . '</div>';								
				$content .= '<div><a href="' . $congress->contact_form . '" target="_blank">Contact Form</a></div>';					
				$content .= '<div><a href="https://www.youtube.com/' . $congress->youtube_id . '" target="_blank">YouTube</a></div>';
				$content .= '<div><a href="https://twitter.com/' . $congress->twitter_id . '" target="_blank">Twitter</a></div>';				
				$content .= '</li>';
			}
		$content .= '</ul>';
		
		return $content;
	}		
	
}

// Search block for a zip search
function find_congressperson_zip() {

	drupal_add_js(drupal_get_path('module', 'find_congressperson') .'/js/find-congressperson.js');
	
	$content = "<div class=\"find-zip row\">";
	
		$content .= '<div class="columns">';
			$content .=  '<div class="subheader">Please enter a 5 digit zipcode</div>';  		
			$content .=  '<input id="zipcode-value" class="zipcode-field" type="text" name="zip" maxlength="5">'; 
			$content .=  '<input type="submit" value="Search" class="zip-button">'; 						
		$content .= '</div>';
		
		return $content;
}

// Search block for a address search
function find_congressperson_address() {

	drupal_add_js(drupal_get_path('module', 'find_congressperson') .'/js/find-congressperson.js');
	
	$zipcode = isset($_GET["zip"]) ? $_GET["zip"] : '';
	
			$content = "<div class=\"find-zip row\">";
				$content .=  '<div class="large-12 columns subheader">Please enter your address to find your congressperson.</div>';
					$content .=  '<div class="large-9 columns">';
					$content .=  '<div class="large-6 columns"><input id="address-value" class="address-field large-6 columns" placeholder="Address" type="text" name="address" maxlength="200"></div>';
					$content .=  '<div class="large-6 columns"><input id="city-value" class="city-field large-6 columns" placeholder="City" type="text" name="city" maxlength="100"></div>';
					$content .=  '<div class="large-6 columns"><input id="state-value" class="state-field large-6 columns" placeholder="State" type="text" name="state" maxlength="2"></div>';
					$content .=  '<div class="large-6 columns"><input id="zipcode-value" class="zipcode-field large-6 columns" placeholder="Zip" value="'. $zipcode .'" type="text" name="zip" maxlength="5"></div>';
				$content .=  '</div>';  														
				$content .=  '<div class="large-3 columns">';
					$content .=  '<input type="submit" value="Search" class="address-button">';
				$content .=  '</div>';	 
			$content .= '</div>';		
		return $content;
}

// Search block for a name search
function find_congressperson_name() {

/* 	drupal_add_js(drupal_get_path('module', 'find_congressperson') .'/js/find-congressperson.js'); */
	
	$content = "<div class=\"find-name row\">";
	
		$content .= '<div class="columns left large-6">';
			$content .=  '<div class="subheader">Please enter the name of the Senator or Representative you are looking for. The member\'s first name may or may not be the name they are usually called.</div>';  		
			$content .=  '<input id="firstname-value" class="firstname-field large-12 columns" placeholder="First Name" type="text" name="firstname" maxlength="200">';
			$content .=  '<input id="lastname-value" class="lastname-field large-12 columns" placeholder="Last Name" type="text" name="lastname" maxlength="100">'; 
			$content .=  '<input type="submit" value="Search" class="name-search-button large-3 columns">'; 						
		$content .= '</div>';
	$content .= '</div>';		
		return $content;
}


// This is the individual Congressperson page
function congressperson() {
	
	$cong_firstname = isset($_GET["first_name"]) ? $_GET["first_name"] : 0;
	$cong_lastname = isset($_GET["last_name"]) ? $_GET["last_name"] : 0;
	$cong_bioguide = isset($_GET["bioguide_id"]) ? $_GET["bioguide_id"] : 0;

	drupal_set_title(t($cong_firstname . ' ' . $cong_lastname));

	$apikey = variable_get('find_congressperson');
	
	// construct the query with our apikey and the query we want to make
	$endpoint = 'https://congress.api.sunlightfoundation.com/legislators?first_name=' . $cong_firstname . '&last_name='. $cong_lastname .'&bioguide_id=' . $cong_bioguide .'&apikey=' . $apikey;
	
	// setup curl to make a call to the endpoint
	$session = curl_init($endpoint);
	
	// indicates that we want the response back
	curl_setopt($session, CURLOPT_RETURNTRANSFER, true);
	
	// exec curl and get the data back
	$data = curl_exec($session);
	
	// remember to close the curl session once we are finished retrieveing the data
	curl_close($session);
	
	// decode the json data to make it easier to parse the php
	$search_results = json_decode($data);
	if ($search_results === NULL) die('Error parsing json = Endpoint Error');
	
	if (empty($search_results->results)) {
	
		$content = '<div class="large-12 columns alert-box alert">Please check your zip code and make sure it is a 5 digit US Postal Zip Code.</div>';
		$content .= '<br><br><br><br>';
		return $content;	
				
	} else {
	// play with the data!
		$congressperson = $search_results->results;
	
		$content = "<div class=\"congress-wrap row\">";
		$congress_checks = variable_get('congressperson_features');	
		$content .= '<ul class="large-12 columns">';			
			foreach ($congressperson as $congress) {				
				$content .= '<img src="http://theunitedstates.io/images/congress/225x275/' . $congress->bioguide_id . '.jpg">';				
				$content .=  '<div>' . $congress->state_name . '</div>';			
				$content .= '<div>Party: ' . $congress->party . '</div>';						
				if (isset($congress->district)) {
					$content .= '<div>District: ' . $congress->district . '</div>';
				}						
				$content .= '<div>Chamber: ' . $congress->chamber . '</div>';					
				$content .= '<div>Open Congress Email: ' . $congress->oc_email . '</div>';													
				$content .= '<div>Facebook: <a href="https://www.facebook.com/' . $congress->facebook_id . '" target="_blank">Facebook Page</a></div>';
				$content .= '<div>Phone: ' . $congress->phone . '</div>';					
				$content .= '<div>Fax: ' . $congress->fax . '</div>';								
				$content .= '<div><a href="' . $congress->contact_form . '" target="_blank">Contact Form</a></div>';					
				$content .= '<div><a href="https://www.youtube.com/' . $congress->youtube_id . '" target="_blank">YouTube</a></div>';
				$content .= '<div><a href="https://twitter.com/' . $congress->twitter_id . '" target="_blank">Twitter</a></div>';				
				$content .= '</li>';
			}
		$content .= '</ul>';
		
		return $content;
	}		
	
}

/**
 * Implements hook_block_info().
 */
function find_congressperson_block_info() {
	$blocks['find_congressperson_block_1'] = array(
		'info' => t('Find Your Congressperson Zip'),
		'cache' => DRUPAL_NO_CACHE,
	); 
	$blocks['find_congressperson_block_2'] = array(
		'info' => t('Find Your Congressperson Full Address'),
		'cache' => DRUPAL_NO_CACHE,
	);   
	$blocks['find_congressperson_block_3'] = array(
		'info' => t('Find Your Congressperson By Full Name'),
		'cache' => DRUPAL_NO_CACHE,
	); 	
	return $blocks;
}
 
/**
 * Implements hook_block_view().
 */
function find_congressperson_block_view($delta = '') {
  $block = array();
  switch ($delta) {
    case 'find_congressperson_block_1': 
      $block['subject'] = t('Find Your Congressperson');
      $block['content'] = find_congressperson_zip();
      break;    
    case 'find_congressperson_block_2': 
      $block['subject'] = t('Find Your Congressperson by Address');
      $block['content'] = find_congressperson_address();
      break;  
    case 'find_congressperson_block_3': 
      $block['subject'] = t('Find Your Congressperson by Name');
      $block['content'] = find_congressperson_name();
      break;              
  }
  return $block;
}

?>